services:
  NSO:
    image: nso-devnet/reservable-sandbox:${NSO_VERSION}
    user: "developer"
    environment:
      - EXTRA_ARGS=--heart
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: "unless-stopped"
    cap_add:
      - NET_ADMIN
    healthcheck:
      test:
        ["CMD-SHELL", "ncs_cmd -c 'wait-start 2' && pgrep -u developer sshd"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 10s
